#pragma once

#define RLM_KEY_ESCAPE             256
#define RLM_KEY_ENTER              257
#define RLM_KEY_TAB                258
#define RLM_KEY_BACKSPACE          259
#define RLM_KEY_INSERT             260
#define RLM_KEY_DELETE             261
#define RLM_KEY_RIGHT              262
#define RLM_KEY_LEFT               263
#define RLM_KEY_DOWN               264
#define RLM_KEY_UP                 265
#define RLM_KEY_PAGE_UP            266
#define RLM_KEY_PAGE_DOWN          267
#define RLM_KEY_HOME               268
#define RLM_KEY_END                269
#define RLM_KEY_CAPS_LOCK          280
#define RLM_KEY_SCROLL_LOCK        281
#define RLM_KEY_NUM_LOCK           282
#define RLM_KEY_PRINT_SCREEN       283
#define RLM_KEY_PAUSE              284
#define RLM_KEY_F1                 290
#define RLM_KEY_F2                 291
#define RLM_KEY_F3                 292
#define RLM_KEY_F4                 293
#define RLM_KEY_F5                 294
#define RLM_KEY_F6                 295
#define RLM_KEY_F7                 296
#define RLM_KEY_F8                 297
#define RLM_KEY_F9                 298
#define RLM_KEY_F10                299
#define RLM_KEY_F11                300
#define RLM_KEY_F12                301
#define RLM_KEY_F13                302
#define RLM_KEY_F14                303
#define RLM_KEY_F15                304
#define RLM_KEY_F16                305
#define RLM_KEY_F17                306
#define RLM_KEY_F18                307
#define RLM_KEY_F19                308
#define RLM_KEY_F20                309
#define RLM_KEY_F21                310
#define RLM_KEY_F22                311
#define RLM_KEY_F23                312
#define RLM_KEY_F24                313
#define RLM_KEY_F25                314
#define RLM_KEY_KP_0               320
#define RLM_KEY_KP_1               321
#define RLM_KEY_KP_2               322
#define RLM_KEY_KP_3               323
#define RLM_KEY_KP_4               324
#define RLM_KEY_KP_5               325
#define RLM_KEY_KP_6               326
#define RLM_KEY_KP_7               327
#define RLM_KEY_KP_8               328
#define RLM_KEY_KP_9               329
#define RLM_KEY_KP_DECIMAL         330
#define RLM_KEY_KP_DIVIDE          331
#define RLM_KEY_KP_MULTIPLY        332
#define RLM_KEY_KP_SUBTRACT        333
#define RLM_KEY_KP_ADD             334
#define RLM_KEY_KP_ENTER           335
#define RLM_KEY_KP_EQUAL           336
#define RLM_KEY_LEFT_SHIFT         340
#define RLM_KEY_LEFT_CONTROL       341
#define RLM_KEY_LEFT_ALT           342
#define RLM_KEY_LEFT_SUPER         343
#define RLM_KEY_RIGHT_SHIFT        344
#define RLM_KEY_RIGHT_CONTROL      345
#define RLM_KEY_RIGHT_ALT          346
#define RLM_KEY_RIGHT_SUPER        347
#define RLM_KEY_MENU               348